CXX = g++
CC = $(CXX)
CXXFLAGS = -std=c++11 -Wall
all:TestAffichable

TestAffichable: TestAffichable.o 

TestAffichable.o: TestAffichable.cc Affichable.h 

Affichable.o: Affichable.cc Affichable.h
 

